# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/eyd/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/eyd/nix";
      fsType = "zfs";
    };

  fileSystems."/per" =
    { device = "rpool/eyd/per";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D45A-F5AE";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/fesch" =
    { device = "/dev/disk/by-uuid/315e4deb-50bb-4f36-89af-f9def614ed8d";
      fsType = "ext4";
    };

  # fileSystems."/mnt/2tb" =
  #   {
  #     device = "/dev/disk/by-uuid/315e4deb-50bb-4f36-89af-f9def614ed8d";
  #     fsType = "ext4";
  #   };

  swapDevices = [ ];
  # swapDevices =
  #   [{ device = "/dev/disk/by-uuid/2a7d1fdc-839a-478c-89a7-86feb62971c8"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp38s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
