name: Check

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          key_encoded: ${{ secrets.KEY }}
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes pipe-operators
            substituters = https://cache.nixos.org/ https://git.lix.systems/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= git.lix.systems:aGVsbG8K
            allow-import-from-derivation = true
            accept-flake-config = true
      - run: nix flake check
