name: Update Repository Tree

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'  # Skip when only README.md is changed

jobs:
  update-readme:
    # Skip if committed by the bot
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tree
        id: install
        run: |
          sudo apt-get update && sudo apt-get install -y tree
          tree --version

      - name: Generate Repository Tree
        id: generate
        if: success()
        run: |
          echo ".
          $(tree -L 4 -I 'result|target|.git|secrets|wallpapers' --charset=ascii | sed '$d')" > repo_tree.txt

      - name: Update README
        id: update
        if: success()
        run: |
          # Create temporary file
          touch README.md.tmp
          
          while IFS= read -r line; do
            if [[ "$line" == '```tree' ]]; then
              echo '```' >> README.md.tmp  # Close the previous block
              echo '```plaintext' >> README.md.tmp  # Open new block with plaintext
              cat repo_tree.txt >> README.md.tmp
              skip=1
            elif [[ "$line" == '```' && "$skip" == 1 ]]; then
              echo "$line" >> README.md.tmp
              skip=0
            elif [[ "$skip" != 1 ]]; then
              echo "$line" >> README.md.tmp
            fi
          done < README.md
          
          # Replace original with new content
          mv README.md.tmp README.md
          
          # Clean up
          rm -f repo_tree.txt

      - name: Commit Changes
        id: commit
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Set up HTTPS remote with token
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          
          # Stage only README.md changes
          git add README.md
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update repository tree"
            git push origin HEAD:main
          fi