name: Update Repository Tree

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate Repository Tree
        run: |
          tree -L 4 -I 'result|target|.git|secrets' --charset=ascii > repo_tree.txt

      - name: Update README
        run: |
          awk '
            /```lang-markdown/ {p=1; print; next}
            /```/ {p=0}
            !p
          ' README.md > README.md.tmp
          sed -i '/```lang-markdown/r repo_tree.txt' README.md.tmp
          mv README.md.tmp README.md

      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update repository tree"
